### ISSUE TITLE
Image and gif searching are broken since latest update

### ISSUE THREAD

**Issue by SteamingMutt** [SteamingMutt/DougleyBot#17]
When `!image` or `!gif` is issued, the bot doesn't know how to handle the request and crashes.

Log output for `!gif`
```        
get_gif(tags, function(id) {
      ^

ReferenceError: get_gif is not defined
    at Object.Commands.gif.process (C:\Users\super\Documents\GitHub\DougleyBot\commands.js:67:9)
    at Client.<anonymous> (C:\Users\super\Documents\GitHub\DougleyBot\discord_bot.js:121:26)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at WebSocket.websocket.onmessage (C:\Users\super\Documents\GitHub\DougleyBot\node_modules\discord.js\lib\Client.js:42:591)
    at WebSocket.onMessage (C:\Users\super\Documents\GitHub\DougleyBot\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:414:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (C:\Users\super\Documents\GitHub\DougleyBot\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:797:10)
    at C:\Users\super\Documents\GitHub\DougleyBot\node_modules\discord.js\node_modules\ws\lib\Receiver.js:473:18
```

Log output for `!image`

```
        this.request("http://ajax.googleapis.com/ajax/services/search/images?v=1.0&q=" + (query.replace(/\s/g, '+')) + "&start=" + page, function(err, res, body) {
                                                                                                ^

TypeError: query.replace is not a function
    at GoogleImagePlugin.respond (C:\Users\super\Documents\GitHub\DougleyBot\google_image_plugin.js:22:90)
    at Object.Commands.image.process (C:\Users\super\Documents\GitHub\DougleyBot\commands.js:165:29)
    at Client.<anonymous> (C:\Users\super\Documents\GitHub\DougleyBot\discord_bot.js:121:26)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at WebSocket.websocket.onmessage (C:\Users\super\Documents\GitHub\DougleyBot\node_modules\discord.js\lib\Client.js:42:591)
    at WebSocket.onMessage (C:\Users\super\Documents\GitHub\DougleyBot\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:414:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (C:\Users\super\Documents\GitHub\DougleyBot\node_modules\discord.js\node_modules\ws\lib\WebSocket.js:797:10)
```

**Comment by SteamingMutt** [comment]
If the problems are too difficult to fix, we could revert back to the previous command receiver.

**Comment by SteamingMutt** [comment]
Update reverted, issue no longer present.
