### ISSUE TITLE
Gif sometimes makes the script crash on the server

### ISSUE THREAD

**Issue by SteamingMutt** [SteamingMutt/DougleyBot#29]
Could be API related, applied at Giphy for a production API key.

**Comment by SteamingMutt** [comment]
```
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function._load (/root/DougleyBot/node_modules/pmx/lib/transaction.js:41:60)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at get_gif (/root/DougleyBot/discord_bot.js:637:23)
    at Object.commands.gif.process (/root/DougleyBot/discord_bot.js:134:7)
    at Client.<anonymous> (/root/DougleyBot/discord_bot.js:540:9)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
```

**Comment by SteamingMutt** [comment]
Seems to be a Linux issue, Windows works fine, investigating.

**Comment by SteamingMutt** [comment]
Disabled gif for the time being

**Comment by SteamingMutt** [comment]
Fixed
